name: Free disk space

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Reclaiming disk space
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile
          
      - name: Creating worker space
        run: |
          sudo mkdir -p /work
          sudo chown -R runner:docker /work
          ls -la / 
          
      - name: Checking if variable survived
        run: echo $GITHUB_WORKSPACE
      
      - uses: actions/checkout@v2
        env:
          GITHUB_WORKSPACE: /work
       
      - name: Listing files
        run: |
          ls -laR / 

          
