name: Free disk space

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Reclaiming disk space
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile
          
      - name: Creating worker space
        run: |
          sudo mkdir -p /work
          sudo chown -R runner:docker /work
          ls -la / 
          export GITHUB_WORKSPACE=/work
          echo $GITHUB_WORKSPACE
          
      - name: Checking if variable survived
        run: echo $GITHUB_WORKSPACE
          
