name: Free disk space

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Reclaiming disk space
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile
          
      - name: Listing disk space
        run: |
          sudo df -h
          sudo rm -rf /usr/share/dotnet
          sudo df -h
          
      - name: Listing files
        run: |
          sudo du -a / | sort -n -r | head -n 50
          
      - name: Creating worker space
        run: |
          sudo mkdir -p /work
          sudo chown -R runner:docker /work
          ls -la /
          echo $GITHUB_WORKSPACE
          pwd
          ls -la $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
                  
      - name: Testing
        run: echo $GITHUB_WORKSPACE
        
      - name: Running symlink
        run: ln -s /work $GITHUB_WORKSPACE/largefs
        
      - uses: actions/checkout@v2
        with:
          path: largefs/src
       
      - name: Listing files
        run: |
          ls -laR $GITHUB_WORKSPACE/largefs/

          
