name: Free disk space

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Listing
        run: ls -la
        
      - name: Test
        run: echo "ok" > file.txt
                
      - name: Downloading clang
        run: curl -s https://raw.githubusercontent.com/chromium/chromium/master/tools/clang/scripts/update.py | python - --output-dir=.

      - name: Listing
        run: ls -la
