name: Test emulator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: create dir
      run: mkdir -p screenshots

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: |
          adb shell screencap -p /sdcard/screencap.png && adb pull /sdcard/screencap.png screenshots/screen.png
          adb shell screenrecord --time-limit=12 /sdcard/test.mp4 && adb pull /sdcard/test.mp4 screenshots/test.mp4

    - uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: screenshots

      
