name: Free disk space

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Init docker
        run: brew install docker docker-compose docker-machine xhyve docker-machine-driver-xhyve
        
      - name: Give perms
        run: |
          sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
          sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve  
          
      - name: Booting machine
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso
          while ! docker-machine create --driver xhyve default; do
            docker-machine rm -f default
            sleep 1;
          done
          
      - name: Testing machine
        run: docker-machine ssh default id -un
      
      - name: Running
        run: docker run --name ubuntu ubuntu:eoan ls -la
      
      - name: Listing
        run: docker --version
        
      - name: Test
        run: echo "ok" > file.txt
                
      - name: Downloading clang
        run: curl -s https://raw.githubusercontent.com/chromium/chromium/master/tools/clang/scripts/update.py | python - --output-dir=.

      - name: Listing
        run: ls -la
