name: Test emulator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: download apk
      run: wget https://github.com/kiwibrowser/android/releases/download/20191007/Kiwi-20191007091034-arm64.apk
    
    - name: create dir
      run: mkdir -p screenshots

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86_64
        script: |
          adb install ./Kiwi-20191007091034-arm64.apk
          adb shell monkey -p com.kiwibrowser.browser -v 500 &
          adb shell screenrecord --time-limit=35 /sdcard/test.mp4 && adb pull /sdcard/test.mp4 screenshots/test.mp4

    - uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: screenshots

      
