name: Test emulator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: create dir
      run: mkdir -p screenshots

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: adb shell screencap -p | sed 's/\r$//' > screenshots/screen.png

    - uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: screenshots

      
